version: "3.4"

services:
  v2ray:
    build: .
    image: v2ray:alpine
    container_name: v2ray
    restart: always
    volumes:
      - ./v2ray-core/config:/etc/v2ray

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/www/html:/var/www/html
      - ./nginx/config:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencryp